### PR TITLE
legends and scales

### LINKED ISSUE #23: Color legend.
When using a color legend (e.g., #2 #19), should we automatically include a nice [legend](https://observablehq.com/@d3/color-legend) (probably yes)?

### LINKED ISSUE #236: radius legend?
This might be a bit difficult to do (do we want superposed circles? how to chose the reference values? even by hand it's difficult…), and it would in any case need inferRadialRange (#235) to be feasible.

related #23

### PR DESCRIPTION
**Pull request by Fil**
(rebased #432)

build at https://observablehq.com/@fil/plot-color-legend-484

closes #23
closes #236

related: #397 #92 #425

TODO:
- [ ] split "expose scales" from "legends"
- [ ] add legend for **threshold** and **quantile** scales
- [x] check polylinear color scales (#530)
  - merged locally
- [ ] check legend for all the diverging scales
- [ ] color legends with a date domain
- [ ] more tests
- [ ] document exhaustively

### CODE REVIEW

**Comment by yurivish** [comment]
Is there a way to configure the positioning of the legend with respect to the plot, e.g. above or below?

**Comment by Fil** [comment]
No, there is no such thing for the moment. We'll probably want some configurability but we don't want to invent a new layout engine :) What you can already do, is to create the legend separately (as shown in a few of the [examples](https://observablehq.com/d/c324a9a466e66329)). Alternatively, move it inside the figure element with d3.select?.

**Comment by mbostock** [comment]
I wanted to work on landing exposing scales first before tackling legends. Ref. https://github.com/observablehq/plot/pull/425#issuecomment-892270954

**Comment by Fil** [comment]
In the two other branches we had accumulated quite a bit of conflict with main, and I wanted to clear that. But feel free to remove anything from this PR (I think the legend part is well separated).

About the issue of exposing Plot.scale(options) or not, I think that there will be a way around in any case if we expose the d3 scale: something like `Plot.plot({ color: options }).scales.color.scale`.

**Comment by mbostock** [comment]
My preference for scales would be to just expose the materialized options (type, domain, range, etc.) with the goal of being able to take a scale constructed from one chart and propagate it to another chart; I would prefer not to expose a D3 scale instance or a scale function. We removed most of the need for that in #280 by precomputing the scaled channels, though scales still have access to the scale functions… which is a little messy. In my ideal world the implementation of scales would be hidden so that we have more flexibility in changing the implementation.

**Comment by Fil** [comment]
I'm good with this plan (including _not_ exposing the d3 scale); it still gives enough information to re-create the scale outside of Plot if necessary.

**Comment by mbostock** [comment]
Superseded by #539.

**Pull request closed without merging**
