### PR TITLE
select{First,Last}[XY]

### LINKED ISSUE #988: Select last defined value (for some given channel)?
E.g., https://observablehq.com/@tophtucker/generations-on-google-trends

```js
Plot.text(
  data.filter((d) => d.generation !== "boomer"),
  Plot.select(
    {
      y: function* (I, Y) {
        for (let i = I.length - 1; i >= 0; --i) {
          const j = I[i];
          if (!isNaN(Y[j])) {
            yield j;
            return;
          }
        }
      }
    },
    Plot.windowY({
      x: "date",
      y: "value",
      k: 5,
      reduce: "mean",
      fill: "generation",
      text: "generation",
      textAnchor: "start",
      dx: 5
    })
  )
)
```

### PR DESCRIPTION
**Pull request by mbostock**
Fixes #988.

### CODE REVIEW

**Review by tophtucker — APPROVED** [review]
❤️ 

so window leaves undefined points rather than changing the length of the data array? e.g. as you change the k of a Plot.windowY, the extent of the x-axis won't change, it'll just get empty bits at the ends. those points have x values but not y values, right?

when i was struggling earlier, i think i actually tried Plot.selectLastX to see if it'd work. but it'd actually be Plot.selectLastY in my case, right? i think i guessed X because it's the last along the x-axis — but no, it's selectLastY because Y is what has to be _defined_.

to position a text label in x and y at the end of the line, i really need the last point where _both_ x and y are defined, right? but one should always imply the other, unless you have weird gappy stuff.

i'm trying to think of when i wouldn't want regular selectLast to have this behavior. maybe something like: i have multi-line chart of stock prices, and wanna put a dot for the current price, but if a stock was delisted a year ago i don't want a dot at the end of that line because that wouldn't be current; its current price is truly undefined.

**Comment by Fil** [comment]
Very much needed. But let me suggest a more generic alternative in #991.

**Review by Fil — COMMENTED** [review]
I'm still not sold on this idea.

It feels like the beginning of an intractable DSL (selectMaxXYRFillOpacity?).

With #993 (and #996 (?)) the original motivation [⌾](https://github.com/observablehq/plot/issues/988) for this change has been solved.

<del>Also, I forgot to mention this alternative:
>     Plot.selectMaxX({ x: "date", y: "unemployment", filter: "unemployment" })
</del>

**Comment by Fil** [comment]
You're right, the alternative only works on the original data, not in the OP.

**Pull request closed without merging**
