### PR TITLE
Ignore polygonStart when computing the bounds of the projected domain

### PR DESCRIPTION
**Pull request by Fil**
**Context.** Plot follows D3 and TopoJSON’s convention for polygon winding order. A polygon that describes the outline of an island should be walked as south->west->north->east->south (SWNE).

However, users sometimes have files that follow the opposite direction. The same island will be walked in the SENW order. This might happen because the shape was drawn in a geojson editor which doesn't care about winding order, or because another piece of code follows the convention adopted by [RFC 7946](https://www.rfc-editor.org/rfc/rfc7946#section-3.1.6), which is the opposite of D3’s (see [d3-geo](https://github.com/d3/d3-geo/blob/main/README.md)). 

For Plot (and D3), this describes the exterior of the island, and not its interior. This PR doesn't change that (see #1141 for discussion of a rewind helper). 

**What this PR changes** is the "fit to domain" approach when the domain has the "wrong" winding order. When we fit the projection, we consider all polygons as outlines only instead of areas. As a consequence, the map is centered on our island, where previously it was fitting to the whole sphere. As a bonus, since we bypass polygon interpolation the fitSize operation is now faster.

The test case and example is a simplified geometry of the Hawaiian islands in the "wrong" winding order. Before, they would result in fit-to-sphere map; now the fit is correct. (However each island is still painted "out", if you have a fill option, which explains the weird colors.)

*before*
hawaii before

*after*
hawaii after

### CODE REVIEW

**Comment by mbostock** [comment]
I don’t think we should change this. The before case is technically correct and it’s what we want for cases like ocean polygons. The after is still broken so you’d have to fix the winding order anyway.

**Comment by Fil** [comment]
In defense of this PR:
- it's a recurring situation and it's hard for users to understand what's wrong and how to fix it
- for the ocean polygon I'd argue you'd use `domain: {type:"Sphere"}`
- the result is only broken if you try to fill the polygon; for stroke, it's fine.

If you're not convinced, I'll try to come up with a working (opt-in) solution for #1141. In either case it's not a blocker.

**Comment by mbostock** [comment]
I like the idea of an option that controls this behavior (i.e., automatically reversing the winding order to ensure that polygons are less than one hemisphere in area), and that we should be consistent when rendering and computing the automatic domain.

**Comment by Fil** [comment]
The approach outlined in https://observablehq.com/@fil/rewind seems better to address #1141.

**Pull request closed without merging**
