### PR TITLE
rename null to “identity” and “identity” to “planar”

### LINKED ISSUE #1155: inconsistent definition of identity between scales and projections
For regular scales (e.g. x, y, color), "identity" is meant to opt out of any scaling and pass raw values. For projections, this is what _null_ does, and identity means a planar-rescalable projection.

Suggestion to rename the _null_ projection to "identity", and the identity projection to "planar". Another idea would be "planar-up" (for the current "reflect-y") and "planar-down" (for the current "identity").

### PR DESCRIPTION
**Pull request by mbostock**
Supersedes #1160. Same tests. Only a trivial change is needed to src/projection.js since we already have different code paths for null vs. the identity projection.

Fixes #1155.

### CODE REVIEW

**Comment by mbostock** [comment]
I’m not sure “planar” is the best name here, since [planar projections](https://en.wikipedia.org/wiki/Planar_projection) are already a thing. This projection only supports translate and scale. It might be better described as a [rigid body transformation](https://en.wikipedia.org/wiki/Rigid_transformation) or a (special case of) [affine transformation](https://en.wikipedia.org/wiki/Affine_transformation).

**Comment by mbostock** [comment]
Or maybe `projection: "transform"`?

**Comment by Fil** [comment]
transform sounds very generic; maybe just "plane"?

**Comment by mbostock** [comment]
I also thought about `projection: "fit"` since the only reason to use this over `projection: null` would be to fit to a given domain. But I think I’m leaning towards either `projection: "affine"` or leaving it as-is.

**Comment by Fil** [comment]
I like "fit" a lot!! I also like "plane" and "planar", but not so much "affine" as it would over-promise.

**Comment by mbostock** [comment]
I don’t feel confident enough to change things here, so we’re going to leave it as-is. I think it’ll be fine.

**Pull request closed without merging**
