### PR TITLE
Interactions: brush

### LINKED ISSUE #5: Brushing.
Brush a rectangular region to select data.

### PR DESCRIPTION
**Pull request by Fil**
Fixes #5.

TODO

- [x] Update the plot’s value on interaction, and emit an *input* event
- [x] Set the value on the figure when the svg is wrapped (#717)
- [x] Support faceting (either with unioned or exclusive brushes)  (#717)
- [x] Allow brush styling (stroke, strokeWidth, strokeOpacity, fill, fillOpacity, _etc._)?
- [x] Decide what happens if multiple marks expose selections: the last one wins (mostly).
- [x] ~~Disable the standard mark channels (*e.g.*, href, title)?~~ No, just don’t do that.
- [x] Set the plot’s initial value when there’s no initial selection
- [x] Improve band scales (select when the band intersects the brush)
- [x] ~~Support scale insets (use scale ranges rather than chart dimensions)?~~ No, it’s fine as is.
- [x] A more explicit cue to indicate that a mark exposes a selection (currently *node*.selection)
- [x] ~~Set the plot’s initial value when there is an initial selection (what about faceting)?~~ Not yet.
- [x] Tests (minimal…)
- [x] Documentation

Previous tests of brush, brushX and brushY: https://observablehq.com/d/2044e02a89cc688a

### CODE REVIEW

**Comment by nami868** [comment]
@Fil My demo report error `TypeError: Plot.brush is not a function`. How do i fix it? Thanks..
image

**Comment by Fil** [comment]
@nami868 are you using a build that includes this code? Plot.brush is not part of the official distribution, it only lives on this development branch. See https://observablehq.com/@fil/plot-early-bird

**Comment by nami868** [comment]
> @nami868 are you using a build that includes this code? Plot.brush is not part of the official distribution, it only lives on this development branch. See https://observablehq.com/@fil/plot-early-bird

thanks

**Comment by Fil** [comment]
superseded by #669

**Comment by mbostock** [comment]
I think this is close. I want to try resurrecting this branch, making a few tweaks, and thinking about the ownerSVGElement problem. We can keep thinking about the selection channel in #669 but we may be able to land brushing (and perhaps pointing? or lasso?) ahead of that.

**Comment by mbostock** [comment]
Idle musing: I wonder if marks could emit _events_?

Also: When brushing with faceting, I could imagine a mode where you can have multiple brushes active, and the selection is the union across facets.

**Comment by mbostock** [comment]
Okay, I think this is ready to go @Fil. It’s missing the ability to set the initial selection, but I think this is still a fine starting point.

**Review by mbostock — APPROVED** [review]
LG! Fil, since you opened this, can you just comment on whether you approve?

**Comment by Fil** [comment]
Yes! 🚀

**Comment by mishatsvelik** [comment]
Regarding faceting, how about supporting an option which synchronises the brush area across all facets? Why is this useful? For example lets say we have plot.line faceted and we use brush.x to select points of comparison between the right-most point in the brush area vs the left most point let's say these are dates in a time-series

**Comment by mishatsvelik** [comment]
Also just realised it does not seem to work with time scale

**Comment by Fil** [comment]
rebooting this with https://observablehq.com/@observablehq/plot-brush-interaction-dev

**Pull request merged**
