### PR TITLE
fix crash on null color legend

### PR DESCRIPTION
**Pull request by Fil**
(refs: #746 & #756)

### CODE REVIEW

**Review by mbostock — CHANGES_REQUESTED** [review]
I don’t think this is the right place to fix this problem (because the issue of a scale being null is not unique to color legends). I think we need to fix it inside `legend`~~or `exposeLegends`~~?

For example, after #756, the `if (isObject(scale))` is no longer sufficient to check whether a scale exists.

**Comment by mbostock** [comment]
Should this return undefined? Or should it throw an error?

```js
Plot.legend({color: {}})
```

I guess it should throw an error (either `unknown legend type` or `missing scale`).

**Comment by Fil** [comment]
I'm fine with both of these choices.

**Comment by mbostock** [comment]
Okay. I think my recommendation is that it behaves the same as `Plot.legend({})` in the sense that there’s no scale defined, which is an error.

**Comment by mbostock** [comment]
This is pretty tricky, because there are three places where we’re using isObject as a proxy for “is a given scale defined?”

At the top-level when iterating over the passed in *options*:

https://github.com/observablehq/plot/blob/08118dd73988250f2b931a43b479ce8f98e07a04/src/legends.js#L16

For a symbol scale to check whether there’s also a color scale:

https://github.com/observablehq/plot/blob/08118dd73988250f2b931a43b479ce8f98e07a04/src/legends.js#L20

In legendsSymbol to check whether there’s also a color scale:

https://github.com/observablehq/plot/blob/08118dd73988250f2b931a43b479ce8f98e07a04/src/legends.js#L26

It makes me wonder if #756 was a mistake since now the test for “is a scale defined” is more involved than testing whether the option exists.

**Comment by mbostock** [comment]
Superseded by #759.

**Pull request closed without merging**
