### PR TITLE
Expose Plot.column and Plot.transform 

### PR DESCRIPTION
**Pull request by Fil**
helpers to create custom transforms (#170)

An example uses Plot.transform to create a uniform sample transform (diamond-carat-sampling)
An example of Plot.column is available at https://observablehq.com/@fil/plot-splom

### CODE REVIEW

**Comment by Fil** [comment]
Rewritten; this time I've left out the renaming of maybeLazyChannel into column, and basic into transform, since it only creates merge conflicts. But when (if) we merge, it would be good to rename these functions internally.

**Comment by mbostock** [comment]
Looks like the documentation needs updating here, since Plot.transform now takes (*options*, *transform*) rather than (...*transforms*)?

**Comment by mbostock** [comment]
Also, do we want to expose maybeLazyChannel here, or lazyChannel? My inclination is that I’d prefer Plot.column to be an alias for the latter, so that a setter function is always returned (even if there is no *source* input).

**Comment by Fil** [comment]
rebased with fixes to the documentation and adoption of lazyChannel instead of maybeLazyChannel.

**Review by mbostock — APPROVED** [review]

**Pull request merged**
