### PR TITLE
handle degenerate domains

### LINKED ISSUE #2210: `TypeError: o[n] is not a function` for empty color domain
I'm setting up a plot where the data set used for the plot may be empty. In such cases, I end up passing `color: { legend: true, domain }` where `domain` is an empty array but this leads to an error. Here's a demo that produces the error due to an empty data set and empty domain https://observablehq.com/d/f1142c360da5114b.

Locally I see:

```
TypeError: I[i2] is not a function
    piecewise piecewise.js:9
    legendRamp ramp.js:95
    legendColor legends.js:53
    createLegends legends.js:76
    plot plot.js:325
    render_chart main.ts:110
    do_query main.ts:278
    onreadystatechange utils.ts:6
    http_get utils.ts:3
    do_query main.ts:263
    query_keystroke main.ts:66
    timeoutId utils.ts:23
    setTimeout handler*debounce/< utils.ts:22
    App main.ts:33
    <anonymous> main.ts:288
```

### PR DESCRIPTION
**Pull request by mbostock**
Fixes #2210. Alternative to #2211.

### CODE REVIEW

**Comment by mbostock** [comment]
Not sure why the test snapshots changed… maybe I’m running a new version of Node? 🤔

**Comment by Fil** [comment]
Yes that's the reason. Same for me aaa8324f790293b84a8b377d6a4092d7ee2c3549 passes all tests with v21.6.0, but not v22.10.0. Probably the maths have changed :)

Means we have to round a bit before we compare numbers… it's going to be fun.

**Comment by Fil** [comment]
can we go back to https://github.com/observablehq/plot/commit/aaa8324f790293b84a8b377d6a4092d7ee2c3549 and leave the tests aside for now? The fix lgtm!

**Comment by mbostock** [comment]
Yeah we’re stuck on Node 20 for development until we either drop node-canvas or they release 3.0.0. #2234 So we’ll need to generate the snapshots on Node 20.

**Review by Fil — APPROVED** [review]
thanks!

**Pull request merged**
