### PR TITLE
type the observable10 color scheme

### PR DESCRIPTION
**Pull request by Fil**

### CODE REVIEW

**Review by mbostock — APPROVED** [review]
Can you keep the categorical schemes in sorted order though?

**Comment by Fil** [comment]
Fixed the order (plus, I had missed the comment!)

**Comment by dperetti** [comment]
Weird, I get this upgrading from 0.6.13 to 0.6.14
image

**Comment by mbostock** [comment]
@dperetti You need to upgrade your transitive dependencies (e.g., [`npm update`](https://docs.npmjs.com/cli/v10/commands/npm-update)).

**Pull request merged**
