### PR TITLE
type=module; update dependencies

### PR DESCRIPTION
**Pull request by mbostock**
Supersedes part of #436; let’s change that PR into just the *mode* reducer.

One interesting review note: the [caltrain.js](https://github.com/observablehq/plot/pull/342/files#diff-34416cfc73a81e12ae863718403dff0d9078500cfb3081af8cb3d8792ccf62ab) test had to be tweaked because it was mixing strings and numbers in the _y_-scale. In D3 6, the numbers were coerced to strings and considered equivalent; in D3 7, ordinal scales now use InternMap which considers these values to be distinct. I like that the code is more explicit now.

### CODE REVIEW

**Comment by Fil** [comment]
I had the same remark for caltrain, which I had changed [differently](https://github.com/observablehq/plot/pull/436/files#diff-34416cfc73a81e12ae863718403dff0d9078500cfb3081af8cb3d8792ccf62ab). I prefer your version (change the data rather than the accessors).

**Comment by Fil** [comment]
I can't build the bundle:

```
❯ yarn prepublishOnly
yarn run v1.22.5
$ rm -rf dist && rollup -c
[!] Error: Package subpath './package.json' is not defined by "exports" in /Users/fil/Sites/plot/node_modules/d3/package.json
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/fil/Sites/plot/node_modules/d3/package.json
    at new NodeError (node:internal/errors:278:15)
    at throwExportsNotFound (node:internal/modules/esm/resolve:321:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:546:3)
    at resolveExports (node:internal/modules/cjs/loader:473:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:513:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:911:27)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/fil/Sites/plot/rollup.config.js:47:12)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

The error message seems to imply that we have to add "./package.json": "./package.json" in d3's exports, but that in turns creates more issues. I'm not sure what's happening.

**Comment by mbostock** [comment]
Strange. You might need Node 14?

**Comment by Fil** [comment]
❯ node -v
v15.5.0

**Comment by mbostock** [comment]
Yea, I hadn’t run prepublishOnly. I can reproduce and will work on a fix.

**Review by Fil — APPROVED** [review]

**Pull request merged**
