### PR TITLE
more support for bigint

### LINKED ISSUE #1297: The stack transform should support BigInt
As a follow-up on #1279, we want this to work:
Capture d’écran 2023-02-28 à 19 20 06

(it currently works if we use y2 instead of y, and skip the stack transform)

cc: @pstuffa

### PR DESCRIPTION
**Pull request by Fil**
I'm not sure this is the right way to do it, but I can't find another way… (we certainly don't want to create a normal array, peek at the values, then convert to typed array).

closes #1297

### CODE REVIEW

**Comment by mbostock** [comment]
I think what we do instead is split the current map function into map and typedMap, where map always returns an Array, and typedMap always returns a given TypedArray. Then, in the typedMap case we compose the given accessor with Number to safely coerce rather than relying on the implicit version which errors. (We could also short-circuit the additional number coercion if the input array is already a TypedArray.)

**Comment by Fil** [comment]
[0d2e2d3](https://github.com/observablehq/plot/pull/1299/commits/0d2e2d3bafd9fda550d05a9c34e6b4b3825359f7) keeps a single entry point (map). Is it enough?

**Comment by mbostock** [comment]
> a single entry point

My thinking was we can easily look for all places that are passing a TypedArray to map and change those to typedMap. That way we don’t need the `type === Array` test (which also isn’t strictly accurate, since you can technically subclass Array or TypedArray, so we’d have to use `isTypedArray` instead).

**Comment by Fil** [comment]
See #1305 for an exploration of typedMap vs. map.

**Review by mbostock — APPROVED** [review]

**Comment by Fil** [comment]
I'll add more unit tests tomorrow and merge.

**Comment by mbostock** [comment]
I added some more tests. 👍 Feel free to add more. I feel confident in this change.

I spent some time thinking we could bypass the coerceNumber call for the integer array types (_e.g._, Uint8Array) since these types have no way of representing NaN, and hence you can’t avoid mapping null to 0. But I was forgetting that the other reason we want coerceNumber is to avoid the error coercing a BigInt to a number, which was the title of this PR, so I threw the work away. 😅

**Pull request merged**
