### PR TITLE
Add rectPath mark and some examples

### PR DESCRIPTION
**Pull request by dgrcode**
I wanted to be able to control the radii of the rect mark individually to be able to create plots like the following:
image

I pretty much copied the rect mark and modified it to render an svg path instead of a rect.

Code could be cleaner –better names for `xC`, `yC`, etc–, and radii using percentages could easily –I think?– implemented.

I've added some tests to show how the radii are exactly the same as when using the rect mark, and that they are pretty much interchangeable. Only difference being this new mark doesn't work with `rx` and `ry` params.

Since this is based on the rect mark, I think the diff between src/marks/rect.js and src/marks/rectPath.js illustrates the changes quite well. Here's that diff:
```diff
diff --git a/src/marks/rect.js b/src/marks/rectPath.js
index 037d631..916d641 100644
--- a/src/marks/rect.js
+++ b/src/marks/rectPath.js
@@ -2,14 +2,7 @@ import {create} from "../context.js";
 import {identity, indexOf, number} from "../options.js";
 import {Mark} from "../plot.js";
 import {isCollapsed} from "../scales.js";
-import {
-  applyDirectStyles,
-  applyIndirectStyles,
-  applyTransform,
-  impliedString,
-  applyAttr,
-  applyChannelStyles
-} from "../style.js";
+import {applyDirectStyles, applyIndirectStyles, applyTransform, applyChannelStyles} from "../style.js";
 import {maybeIdentityX, maybeIdentityY} from "../transforms/identity.js";
 import {maybeTrivialIntervalX, maybeTrivialIntervalY} from "../transforms/interval.js";
 import {maybeStackX, maybeStackY} from "../transforms/stack.js";
@@ -18,7 +11,7 @@ const defaults = {
   ariaLabel: "rect"
 };

-export class Rect extends Mark {
+export class RectPath extends Mark {
   constructor(data, options = {}) {
     const {
       x1,
@@ -30,8 +23,13 @@ export class Rect extends Mark {
       insetRight = inset,
       insetBottom = inset,
       insetLeft = inset,
-      rx,
-      ry
+      borderRadius = 0,
+      borderTopRadius = borderRadius,
+      borderBottomRadius = borderRadius,
+      borderTopLeftRadius = borderTopRadius,
+      borderTopRightRadius = borderTopRadius,
+      borderBottomRightRadius = borderBottomRadius,
+      borderBottomLeftRadius = borderBottomRadius
     } = options;
     super(
       data,
@@ -48,54 +46,112 @@ export class Rect extends Mark {
     this.insetRight = number(insetRight);
     this.insetBottom = number(insetBottom);
     this.insetLeft = number(insetLeft);
-    this.rx = impliedString(rx, "auto"); // number or percentage
-    this.ry = impliedString(ry, "auto");
+
+    // TODO All these could also be %
+    this.borderTopLeftRadius = number(borderTopLeftRadius);
+    this.borderTopRightRadius = number(borderTopRightRadius);
+    this.borderBottomLeftRadius = number(borderBottomLeftRadius);
+    this.borderBottomRightRadius = number(borderBottomRightRadius);
   }
   render(index, scales, channels, dimensions, context) {
     const {x, y} = scales;
     const {x1: X1, y1: Y1, x2: X2, y2: Y2} = channels;
     const {marginTop, marginRight, marginBottom, marginLeft, width, height} = dimensions;
-    const {insetTop, insetRight, insetBottom, insetLeft, rx, ry} = this;
+    const {
+      insetTop,
+      insetRight,
+      insetBottom,
+      insetLeft,
+      borderTopLeftRadius,
+      borderTopRightRadius,
+      borderBottomRightRadius,
+      borderBottomLeftRadius
+    } = this;
     return create("svg:g", context)
       .call(applyIndirectStyles, this, scales, dimensions)
       .call(applyTransform, this, {x: X1 && X2 ? x : null, y: Y1 && Y2 ? y : null}, 0, 0)
-      .call((g) =>
-        g
+      .call((g) => {
+        return g
           .selectAll()
           .data(index)
           .enter()
-          .append("rect")
+          .append("path")
           .call(applyDirectStyles, this)
-          .attr("x", X1 && X2 && !isCollapsed(x) ? (i) => Math.min(X1[i], X2[i]) + insetLeft : marginLeft + insetLeft)
-          .attr("y", Y1 && Y2 && !isCollapsed(y) ? (i) => Math.min(Y1[i], Y2[i]) + insetTop : marginTop + insetTop)
-          .attr(
-            "width",
-            X1 && X2 && !isCollapsed(x)
-              ? (i) => Math.max(0, Math.abs(X2[i] - X1[i]) - insetLeft - insetRight)
-              : width - marginRight - marginLeft - insetRight - insetLeft
-          )
-          .attr(
-            "height",
-            Y1 && Y2 && !isCollapsed(y)
-              ? (i) => Math.max(0, Math.abs(Y1[i] - Y2[i]) - insetTop - insetBottom)
-              : height - marginTop - marginBottom - insetTop - insetBottom
-          )
-          .call(applyAttr, "rx", rx)
-          .call(applyAttr, "ry", ry)
-          .call(applyChannelStyles, this, channels)
-      )
+          .attr("d", (i) => {
+            const xC = X1 && X2 && !isCollapsed(x) ? Math.min(X1[i], X2[i]) + insetLeft : marginLeft + insetLeft;
+            const yC = Y1 && Y2 && !isCollapsed(y) ? Math.min(Y1[i], Y2[i]) + insetTop : marginTop + insetTop;
+            const widthC =
+              X1 && X2 && !isCollapsed(x)
+                ? Math.max(0, Math.abs(X2[i] - X1[i]) - insetLeft - insetRight)
+                : width - marginRight - marginLeft - insetRight - insetLeft;
+            const heightC =
+              Y1 && Y2 && !isCollapsed(y)
+                ? Math.max(0, Math.abs(Y1[i] - Y2[i]) - insetTop - insetBottom)
+                : height - marginTop - marginBottom - insetTop - insetBottom;
+
+            const radii = {
+              topLeft: {
+                x: Math.min(widthC / 2, borderTopLeftRadius),
+                y: Math.min(heightC / 2, borderTopLeftRadius)
+              },
+              topRight: {
+                x: Math.min(widthC / 2, borderTopRightRadius),
+                y: Math.min(heightC / 2, borderTopRightRadius)
+              },
+              bottomRight: {
+                x: Math.min(widthC / 2, borderBottomRightRadius),
+                y: Math.min(heightC / 2, borderBottomRightRadius)
+              },
+              bottomLeft: {
+                x: Math.min(widthC / 2, borderBottomLeftRadius),
+                y: Math.min(heightC / 2, borderBottomLeftRadius)
+              }
+            };
+
+            // start top-left, clockwise
+            const corners = {
+              topLeft: {
+                start: [xC, yC + radii.topLeft.y],
+                end: [xC + radii.topLeft.x, yC]
+              },
+              topRight: {
+                start: [xC + widthC - radii.topRight.x, yC],
+                end: [xC + widthC, yC + radii.topRight.y]
+              },
+              bottomRight: {
+                start: [xC + widthC, yC + heightC - radii.bottomRight.y],
+                end: [xC + widthC - radii.bottomRight.x, yC + heightC]
+              },
+              bottomLeft: {
+                start: [xC + radii.bottomLeft.x, yC + heightC],
+                end: [xC, yC + heightC - radii.bottomLeft.y]
+              }
+            };
+
+            return `m${corners.topLeft.start.join(",")} a${radii.topLeft.x} ${radii.topLeft.y} 0 0 1 ${
+              radii.topLeft.x
+            } -${radii.topLeft.y} H${corners.topRight.start[0]} a${radii.topRight.x} ${radii.topRight.y} 0 0 1 ${
+              radii.topRight.x
+            } ${radii.topRight.y} V${corners.bottomRight.start[1]} a-${radii.bottomRight.x} ${
+              radii.bottomRight.y
+            } 0 0 1 -${radii.bottomRight.x} ${radii.bottomRight.y} H${corners.bottomLeft.start[0]} a-${
+              radii.bottomLeft.x
+            } -${radii.bottomLeft.y} 0 0 1 -${radii.bottomLeft.x} -${radii.bottomLeft.y} z`;
+          })
+          .call(applyChannelStyles, this, channels);
+      })
       .node();
   }
 }

-export function rect(data, options) {
-  return new Rect(data, maybeTrivialIntervalX(maybeTrivialIntervalY(options)));
+export function rectPath(data, options) {
+  return new RectPath(data, maybeTrivialIntervalX(maybeTrivialIntervalY(options)));
 }

-export function rectX(data, options = {y: indexOf, interval: 1, x2: identity}) {
-  return new Rect(data, maybeStackX(maybeTrivialIntervalY(maybeIdentityX(options))));
+export function rectPathX(data, options = {y: indexOf, interval: 1, x2: identity}) {
+  return new RectPath(data, maybeStackX(maybeTrivialIntervalY(maybeIdentityX(options))));
 }

-export function rectY(data, options = {x: indexOf, interval: 1, y2: identity}) {
-  return new Rect(data, maybeStackY(maybeTrivialIntervalX(maybeIdentityY(options))));
+export function rectPathY(data, options = {x: indexOf, interval: 1, y2: identity}) {
+  return new RectPath(data, maybeStackY(maybeTrivialIntervalX(maybeIdentityY(options))));
 }
```

Opening as draft since I don't think this is ready to merge, and I still have to run some checks listed on CONTRIBUTING.md. But I wanted to know what the team thinks about this addition before spending more time on it.

Thanks!

### CODE REVIEW

**Comment by dgrcode** [comment]
Update regarding the checks from CONTRIBUTING.md:
- Prettier didn't add any changes 🎉 
- Coudln't run `yarn test` due to this error:
  ```bash
  TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Users/daniel/projects/opensource/plot/src/format.ts
      at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:71:15)
      at Loader.getFormat (internal/modules/esm/loader.js:104:42)
      at Loader.getModuleJob (internal/modules/esm/loader.js:242:31)
      at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:58:21)
      at async Promise.all (index 34)
      at link (internal/modules/esm/module_job.js:63:9)
  ```

**Comment by dgrcode** [comment]
I'm also just thinking, maybe there's a better DX than a separate mark if we wanted to add it to the library. Maybe there's a simple way to check if one of the `border{location}Radius` is provided, and just internally use the current or the path implementation.

Just thinking out loud here :)

**Comment by Fil** [comment]
I feel that it's a lot of code to support a relatively small feature, and I'm not sure we'd want to support this in the default rect mark—or if we do, we'd probably switch all the shapes from rect to path.

In any case, our goal is to make it easy for anyone to create custom marks (from scratch or as variants of standard marks) in "user space", without having to fork and add code to the library. Have you considered that route?

```
barY2 = (data, options) => {
  const bar = Plot.barY(data, options);

  bar.render = function (index, scales, channels) {
    return …;
  };

  return bar;
}
```

**Comment by dgrcode** [comment]
Thanks for the super quick reply :)

> Have you considered that route?

I hadn't, but that sounds amazing. It actually opens the door for people to publish npm packages with custom plots covering their needs, and sharing them with the community. I think that approach makes a lot of sense.

I'll implement this one in the project I'm working on using the method you mention.

Regarding this PR, I understand we can close it. I'll keep the branch alive in case you want to support that feature at some point. The only updates needed are supporting `rx` and `ry`, which don't map exactly 1-to-1 to the `border{location}Radius` props I added. I'm guessing the following should just work, but haven't checked:
```js
const radii = {
  topLeft: {
    x: rx ?? Math.min(widthC / 2, borderTopLeftRadius),
    y: ry ?? Math.min(heightC / 2, borderTopLeftRadius)
  },
  // and the same for the rest of the radii
};
```

**Pull request closed without merging**
