### PR TITLE
custom grid ticks

### LINKED ISSUE #7: Custom grid density or values.
Currently *grid* is strictly a boolean, but true could be equivalent to the corresponding ticks, a number could compute new ticks (*e.g.*, for higher density) and an array could contain explicit tick values.

### PR DESCRIPTION
**Pull request by Fil**
Fixes #7.

Demo: https://observablehq.com/@observablehq/plot-custom-grid-612

### CODE REVIEW

**Comment by Fil** [comment]
I might go back to one mark per grid tick, which would also help support grid lines with various styles (as in https://github.com/observablehq/plot/issues/114#issuecomment-839899434)

**Comment by Fil** [comment]
Not sure how to design it so that the styles (opacity: 0.1) could be modified through the plot's root _style_ option. It's a generic question though (see #397 #253).

**Review by mbostock — CHANGES_REQUESTED** [review]
If you specify explicit values for the scale’s grid, we should extend the default domain to cover those values. I’d also prefer to stick to the existing attributes, rather than extending the inline stylesheets, for consistency with d3-axis. I’m cool with adding a “grid” class to differentiate these grid lines from ticks, though.

**Comment by Fil** [comment]
superseded by #985

**Pull request closed without merging**
