### PR TITLE
sort groups

### PR DESCRIPTION
**Pull request by Fil**
Don't sort the groups in `Plot.group()`; the only case where it makes a difference is when the groups are stacked, and the stacking order can be made explicit (see test: penguins-species-island).

Ordinal scales now accept a sort option, which can be:
- `"ascending"`: default, sorts in ascending order with undefined first
- false, null (or `input`): sort in input order
- `"count"`: sort by the number of times each ordinal value is present in the marks.

Note: when using Plot.barY the "count" is equal to 1 for each bar—it is *not* the number of times each value is present in the data. However `{sort: "count"}` works well to sort facets, or an ordinal scale for a Plot.dot chart. See the discussion in #388 for more details.

The build and a few examples are available at https://observablehq.com/d/d797c5a9572385bd

### CODE REVIEW

**Comment by Fil** [comment]
90% obsolete after #442 ; but not sorting groups is probably still a good idea

**Comment by Fil** [comment]
Note that #332 also takes care of facet sorting (by count, by input, or by value).

**Comment by mbostock** [comment]
There’s a lot of overlap here with the new *sort* and *filter* options for bin and group #495. But related to #435, we don’t pass the key(s) to the group reducer, so it’s not currently possible to implement the default natural ordering of groups and hence there’s a separate internal sorting that happens prior to the user-specified *sort* reducer. But I think we can make it work…

**Comment by mbostock** [comment]
Removing the sort here also affects the bin transform, since the bin transform groups internally, too (e.g., on *z*). So this is extra tricky: maybe the sort reducer would also need to be passed the group keys *in addition to* the bin extents.

**Comment by mbostock** [comment]
Going to close this as covered by #495, but I recognize there are still things to do (mostly covered by #435).

**Pull request closed without merging**
